server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:file:./db/demoH2
    username: admin
    password: 123456
  h2:
    console:
      enabled: true
      settings.web-allow-others: true
      path: /h2admin
  sql:
    init:
#      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
